name: conventional_power_plants

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.5
  - bokeh=0.12.2
  - matplotlib
  - notebook>=4.2
  - numpy=1.11.1
  - pandas=0.18.1
  - pyproj
  - pyyaml=3.12
  - xlsxwriter
  - xlrd  # pandas: excel i/o
